# Generated by Django 4.1.7 on 2024-01-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
